version: '3' 
services:
  
  server:
    container_name: vw-server
    build: ./server
    volumes:
        - ./server:/usr/src/server
    command: nodemon -L index.js
    expose:
        - 6000
    restart: always
    ports:
        - '6000:6000'
    links:
        - mongo
    environment:
        - PORT=6000
        - CLIENT_ID=57c4ad07-c6f1-4ab8-a5f6-7f9aa26d8b59@apps_vw-dilab_com 
        - CLIENT_SECRET=673bda449f5339f2afb73729ef9c332c0720474c86f2ee0958957ceab2c43632
        - MONGO_URL=mongodb://mongo:27017/vw-okapi
 
  ui:
   build: ./ui
   expose:
     - 3000
   ports:
     - '3000:3000'
   volumes:
     - './ui:/usr/src/app'
     - './usr/src/app/node_modules'
     - './ui/public:/usr/src/app/public'
   links:
     - server

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
